PROGRAM ADD_CHARACTER
IMPLICIT NONE
CHARACTER(LEN=10) :: A,B
INTEGER :: I,J
INTERFACE OPERATOR(+)
	FUNCTION ADD(A,B) RESULT(ADD_RESULT)
		IMPLICIT NONE
		CHARACTER(LEN=*),INTENT(IN) :: A,B
		CHARACTER(LEN=2) :: ADD_RESULT
	END FUNCTION ADD
END INTERFACE
READ  *, A,B
PRINT *, A+B,2+3
END PROGRAM ADD_CHARACTER

FUNCTION ADD(A,B) RESULT(ADD_RESULT)
	IMPLICIT NONE
	CHARACTER(LEN=*),INTENT(IN) :: A,B
	CHARACTER(LEN=2) :: ADD_RESULT
	ADD_RESULT=A(LEN_TRIM(A):LEN_TRIM(A))//B(LEN_TRIM(B):LEN_TRIM(B))
END FUNCTION ADD
