all:
	cd halleffect && $(MAKE)
	cd ledflow && $(MAKE)
	cd lightsensor && $(MAKE)
	cd sw18020p && $(MAKE)
	cd testnano && $(MAKE)
clean:
	cd halleffect && $(MAKE) clean
	cd ledflow && $(MAKE) clean
	cd lightsensor && $(MAKE) clean
	cd sw18020p && $(MAKE) clean
	cd testnano && $(MAKE) clean
