all:
	cd halleffect && $(MAKE)
	cd ledflow && $(MAKE)
	cd lightsensor && $(MAKE)
	cd sw18020p && $(MAKE)
	cd testnano && $(MAKE)
	cd dht11 && $(MAKE)
	cd irtest && $(MAKE)
	cd liquidcrystal && $(MAKE)
	cd tone && $(MAKE)
	cd lm35 && $(MAKE)
	cd ledonboard && $(MAKE)
	cd hmc5883l && $(MAKE)
	cd pir && $(MAKE)
	cd hc_sr04 && $(MAKE)
	cd led && $(MAKE)
	## 5f2d225e-a770-4c12-b2b3-c230d5818085
clean:
	cd halleffect && $(MAKE) clean
	cd ledflow && $(MAKE) clean
	cd lightsensor && $(MAKE) clean
	cd sw18020p && $(MAKE) clean
	cd testnano && $(MAKE) clean
	cd dht11 && $(MAKE) clean
	cd irtest && $(MAKE) clean
	cd liquidcrystal && $(MAKE) clean
	cd tone && $(MAKE) clean
	cd lm35 && $(MAKE) clean
	cd ledonboard && $(MAKE) clean
	cd hmc5883l && $(MAKE) clean
	cd pir && $(MAKE) clean
	cd hc_sr04 && $(MAKE) clean
	cd led && $(MAKE) clean
	## b7b86095-2263-46c8-a9c6-52e52760265c
